"""Changed nullable to true in the about column of the Game table

Revision ID: 65fa1f13f7a4
Revises: b27b5157bc63
Create Date: 2024-05-18 11:14:45.028630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65fa1f13f7a4'
down_revision = 'b27b5157bc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=False)

    # ### end Alembic commands ###
