"""empty message

Revision ID: 7e3dca2209c1
Revises: 3fcb309f51f3
Create Date: 2024-06-17 20:25:30.971642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e3dca2209c1'
down_revision = '3fcb309f51f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_file_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('banner_image_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('trailer_1_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('trailer_2_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('trailer_3_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_1_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_2_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_3_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_4_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_5_link', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_6_link', sa.Text(length=200), nullable=True))
        batch_op.alter_column('summary',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=False)
        batch_op.alter_column('about',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.Text(length=10000),
               existing_nullable=True)
        batch_op.alter_column('game_file',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=False)
        batch_op.alter_column('banner_image',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=False)
        batch_op.alter_column('trailer_1',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('trailer_2',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('trailer_3',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_1',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_2',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_3',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_4',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_5',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_6',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=True)
        batch_op.alter_column('blob_name_prefix',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('blob_name_prefix',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('preview_image_6',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_5',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_4',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_3',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_2',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('preview_image_1',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('trailer_3',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('trailer_2',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('trailer_1',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('banner_image',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('game_file',
               existing_type=sa.Text(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('about',
               existing_type=sa.Text(length=10000),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.Text(length=500),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('preview_image_6_link')
        batch_op.drop_column('preview_image_5_link')
        batch_op.drop_column('preview_image_4_link')
        batch_op.drop_column('preview_image_3_link')
        batch_op.drop_column('preview_image_2_link')
        batch_op.drop_column('preview_image_1_link')
        batch_op.drop_column('trailer_3_link')
        batch_op.drop_column('trailer_2_link')
        batch_op.drop_column('trailer_1_link')
        batch_op.drop_column('banner_image_link')
        batch_op.drop_column('game_file_link')

    # ### end Alembic commands ###
