"""Changed bought_game_id in Review table to game_id

Revision ID: 8554cb726255
Revises: ae082cdc2bd5
Create Date: 2024-06-05 21:19:57.660442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8554cb726255'
down_revision = 'ae082cdc2bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('review_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'game', ['game_id'], ['id'])
        batch_op.drop_column('bought_game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_game_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_ibfk_1', 'bought_game', ['bought_game_id'], ['id'])
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
