"""Finished Game table structure

Revision ID: 88b7f51bfd01
Revises: 8054ca35d72e
Create Date: 2024-05-18 02:36:48.659030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b7f51bfd01'
down_revision = '8054ca35d72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('developer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('about', sa.String(length=10000), nullable=False))
        batch_op.add_column(sa.Column('game_file', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('banner_image', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('trailer_1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('trailer_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('trailer_3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_5', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_image_6', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['developer_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['publisher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('preview_image_6')
        batch_op.drop_column('preview_image_5')
        batch_op.drop_column('preview_image_4')
        batch_op.drop_column('preview_image_3')
        batch_op.drop_column('preview_image_2')
        batch_op.drop_column('preview_image_1')
        batch_op.drop_column('trailer_3')
        batch_op.drop_column('trailer_2')
        batch_op.drop_column('trailer_1')
        batch_op.drop_column('banner_image')
        batch_op.drop_column('game_file')
        batch_op.drop_column('about')
        batch_op.drop_column('summary')
        batch_op.drop_column('release_date')
        batch_op.drop_column('developer_id')
        batch_op.drop_column('publisher_id')

    # ### end Alembic commands ###
