"""Updated User table

Revision ID: 91a8b3a99466
Revises: 9231be3bded3
Create Date: 2024-05-18 00:38:08.233728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a8b3a99466'
down_revision = '9231be3bded3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
