"""Added blob_name_prefix to User model

Revision ID: d8177f2046ab
Revises: ea525f2a5df6
Create Date: 2024-06-04 14:20:16.477752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8177f2046ab'
down_revision = 'ea525f2a5df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blob_name_prefix', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blob_name_prefix')

    # ### end Alembic commands ###
