"""Added blob_name_prefix to Game model

Revision ID: ea525f2a5df6
Revises: 92c8a2b3cee6
Create Date: 2024-06-02 21:24:17.249883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea525f2a5df6'
down_revision = '92c8a2b3cee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blob_name_prefix', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('blob_name_prefix')

    # ### end Alembic commands ###
